language: swift
osx_image: xcode12.2
xcode_project: r2-shared-swift.xcodeproj
xcode_scheme: r2-shared-swift
xcode_destination: platform=iOS Simulator,OS=13.7,name=iPhone X
xcode_sdk: iphonesimulator13.7

branches:
  only:
    - master
    - develop

cache:
  directories:
    - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --use-xcframeworks --platform iOS --cache-builds

script:
  - xcodebuild clean build -quiet
